IDS_TO_EXCLUDE = [456226577798135808] # ID deleted account
ID_MERGE_MAP = {"299257811366576128": ".redhot_",
                  "183303146955735040": "lupoticha"}

NAME_REPLACE_MAP = {
    ".danylo": "Danylo",
    ".emna_": "Enm",
    ".muhu": "Camille",
    ".redhot_": "Léo",
    "144kynn_": "144kynn_",
    "__boba___": "Boba",
    "_noko.": "Nadjy",
    "adriencumulo": "Adrien",
    "aimen9880": "Aimen",
    "akam.e": "Alice",
    "akuuuuuuuuu": "Aku",
    "aniistiti": "Anissa",
    "anita0732": "Anita",
    "antoin.e": "Antoine",
    "ascended_sao": "Sao My",
    "assiox": "Assia",
    "atillux": "Atilla",
    "attits": "Atti",
    "atzporos": "Jason",
    "axel005521": "Axel",
    "batman2715": "Batman",
    "busto_": "Matiya",
    "caeliumz": "Mathis",
    "catnelle": "Safia",
    "chehste": "Este",
    "cynthia_von_bottoks": "Cynthia",
    "darkysama": "Clément",
    "debonairfab": "Debonair Fab",
    "dinoz_": "Nicolas",
    "diploplo": "Diplo",
    "donpatchi": "Donpatchi",
    "doro.otea": "Clara",
    "edward511": "Edward",
    "entap.": "Kelly",
    "ersees": "Yanis",
    "g_remy": "Gérémy",
    "grasdenunu": "Gras de Nunu",
    "hanabiiii": "Tatiana",
    "helskin": "Helskin",
    "hujeau": "Hujeau",
    "irinacitron": "Irina",
    "iskander16": "Iskander",
    "itachill_": "Itachi",
    "jooojx": "Jooj",
    "jubjube": "Yliann",
    "kingu_avocado": "Bilal",
    "kirg0n": "Kirgon",
    "kuruuuka": "Eva",
    "kyky2005": "Kyllian",
    "kyubyyy": "Kyuby",
    "legrosk": "Legrosk",
    "lenatje": "Léna",
    "lilisica": "Pauline",
    "lupoticha": "Lu Man",
    "lxst_nayra": "Nayra",
    "mademoiselle.layla": "Kenza",
    "maelhinio": "Maël",
    "mailyan": "Myan",
    "massieh": "Massieh",
    "may.86.b": "May",
    "menacing_cake": "Menacing Cake",
    "mezouze.": "Mezouze",
    "minasedai": "Mina",
    "mirapv": "Nina",
    "mymyyyyyy": "Mylanne",
    "narabiis": "Gaëlle",
    "nathsus": "Nathan",
    "nightx9": "Hugo",
    "niou": "Lucas",
    "otchi": "Otchi",
    "oxynemesis": "Oxy Nemesis",
    "pikacao": "Pikacao",
    "raijinsen": "Marius",
    "remli_8": "Remi",
    "sabrito_": "Sabri",
    "scotted": "Scotted",
    "seraksan": "Serak",
    "sheimi.": "Valou",
    "simo3329": "Simon3329",
    "simsimz": "Simon",
    "slinlpb": "Nils",
    "sodouille": "Gaylord",
    "solafleur": "Émilie",
    "stanis1018": "Stanis",
    "stef_35": "Stef",
    "tacina": "Tasnime",
    "tenesquik": "Ténébrisse",
    "timiane": "Mélanie",
    "tisema": "Matise",
    "tndstrs4real": "Tetsu",
    "tovounet": "Tov",
    "tuturino_": "Arthur",
    "ussererzada": "Emy",
    "uxtickets": "David",
    "virkos": "Edison",
    "wass9005": "Wass",
    "waykun": "Waykun",
    "woldek": "Woldek",
    "xpulpe": "Sophie",
    "xujing": "Sokat",
    "yassine_ic": "Yassine",
    "zeykoo": "Ali",
    "zumos69": "Zumos",
    "zyoulou": "Zyoulou",
}

SMURF_ACCOUNTS = [
    "daka1845", ".uwu2", "nqtqn", "nathsmurf", "lugrocha", "kdamamadousakho"
]